name: Build and Deploy

on:
  push:

jobs:
  build-deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"
          token: ${{secrets.TOKEN}}

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: "corretto"
          java-version: "17"

      - name: Build Spring Boot Jar
        run: ./gradlew -Pversion=1.0-${GITHUB_SHA:0:8} bootJar
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: krypton-server
          path: ./build/libs/server-*.jar
      - name: Build Docker Image
        run: docker build -t krypton-server:1.0-${GITHUB_SHA:0:8} .
      - name: Login to Docker
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push to Docker
        run: docker push krypton-server:1.0-${GITHUB_SHA:0:8}
